### ISSUE TITLE
[Bug] MEMBER COUNT PLUGIN BROKEN

### ISSUE THREAD

**Issue by zluckytraveler** [Arashiryuu/crap#194]
**Which plugin is this about?**
MEMBER COUNT PLUGIN

**Describe the Bug**
The newest Discord Update Broke all Plugins

**To Reproduce**
Opening Discord Client

**Expected Behavior**
For the plugin to not be broken

**Discord Version**
Stable

**Comment by Xakorik** [comment]
Broken for me too, has compile error when loading.

```
TypeError: Cannot destructure property 'ActionTypes' of 'DiscordConstants' as it is undefined.
    at buildPlugin (betterdiscord://plugins/MemberCount.plugin.js:140:11)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:867:5)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:868:3)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at Object.loadAllAddons (<anonymous>:4:12239)
    at Object.initialize (<anonymous>:4:6705)
    at Object.initialize (<anonymous>:4:36661)
    at Object.startup (<anonymous>:4:381833)
```

**Comment by Slegnor** [comment]
Same issue, since the BetterDiscord 1.8.0 update the MemberCount plugin has broken, same in 1.8.1

![image](https://user-images.githubusercontent.com/11891577/196196134-db7f1085-caff-415f-b67d-6cad2c3c8960.png)

**Comment by idanyas** [comment]
is there any fix?

**Comment by bayshades** [comment]
> Nope. You should remove it. It's no more supported.

Uhm do you know any similar plugin like MemberCount?

**Comment by OnFire124** [comment]
> > Nope. You should remove it. It's no more supported.
> 
> Uhm do you know any similar plugin like MemberCount?

ServerDetails is a alternative ig.

**Comment by Willydaham09** [comment]
same issue, pls fix

**Comment by ColonelGerdauf** [comment]
This is disappointing, as I really missed having the count of members being at the top of the members list.
