### ISSUE TITLE
[Bug] HideUtils could not be compiled.

### ISSUE THREAD

**Issue by hikarisakira** [Arashiryuu/crap#195]
**Which plugin is this about?**

After the plugin installs, it just runs into a compile error. 

**Describe the Bug**

```
TypeError: Cannot destructure property 'openModal' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/HideUtils.plugin.js:119:11)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1547:5)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1548:3)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at Object.loadAllAddons (<anonymous>:4:12239)
    at Object.initialize (<anonymous>:4:6705)
    at Object.initialize (<anonymous>:4:36661)
    at Object.startup (<anonymous>:4:381833)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/110965364/195476432-5cae4ba3-a23d-4e71-9d30-ae00a8d2f5bf.png)

**Discord Version**

Stable, 152131

**Comment by SweetLuna** [comment]
Same issue

**Comment by Kurokroks** [comment]
Same issue

---

**Which plugin is this about?**
HideUtils v2.1.58by Arashiryuu

**Describe the Bug**
Could not be compiled.

**Discord Version**
Stable with BetterDiscord Core v1.8.4

**Additional Context**
TypeError: Cannot destructure property 'openModal' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/HideUtils.plugin.js:119:11)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1547:5)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1548:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by zeus1921** [comment]
please, fix it
![imagem](https://user-images.githubusercontent.com/28808082/213435027-49872447-4f91-42fe-8f4c-b57834dceb32.png)

**Comment by Aida-Enna** [comment]
Any update on this?

**Comment by gothiclolita666** [comment]
Same problem!

**Comment by Newton667** [comment]
yeah same problem.

**Comment by cyrus01337** [comment]
Has the traceback changed at all?

**Comment by ImAFrogOwO** [comment]
if you wanna do it yourslf change line 118
`const { ComponentDispatch: Dispatcher } = WebpackModules.getByProps('ComponentDispatch');`

to
`const { ComponentDispatch: Dispatcher } = BdApi.Webpack.getModule(e => e.dispatch && !e.emitter && !e.commands);`

**Comment by Gecker** [comment]
any chance this would get resolved any time soon?
features of hiding users\servers seem really cool, and I couldn't find that anywhere else.
I tried changing some stuff so it'd at least compile, but in the end it just didn't work, and clicking on buttons in settings crashes discord too.

**Comment by githubjsorg** [comment]
> [@GrummanF-14Tomcat](https://github.com/GrummanF-14Tomcat) [@Aida-Enna](https://github.com/Aida-Enna) [@gothiclolita666](https://github.com/gothiclolita666) [@Newton667](https://github.com/Newton667)
> 
> Has the traceback changed at all from what it was? A screenshot would help.

Here you go.

![Image](https://github.com/user-attachments/assets/f7bf77e8-0725-4ce1-930d-144918672072)
