### ISSUE TITLE
[Bug] HideUtils could not be compiled.

### ISSUE THREAD

**Issue by zeus1921** [Arashiryuu/crap#200]
TypeError: Cannot destructure property 'openModal' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/HideUtils.plugin.js:119:11)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1547:5)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1548:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at AsyncFunction.<anonymous> (<anonymous>:4:6226)

**Comment by Arashiryuu** [comment]
duplicate of #195
