### ISSUE TITLE
[Bug] Doesn`t compile after download

### ISSUE THREAD

**Issue by KuprumLight** [Arashiryuu/crap#207]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
Doesn`t compile.

here is code: 

TypeError: Cannot destructure property 'ActionTypes' of 'DiscordConstants' as it is undefined.
    at buildPlugin (betterdiscord://plugins/MemberCount.plugin.js:140:11)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:867:5)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:868:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)

**Comment by Arashiryuu** [comment]
Known issue, see #194
