### ISSUE TITLE
[Bug] Could not be compiled

### ISSUE THREAD

**Issue by TheEmbracedOne** [Arashiryuu/crap#228]
**Which plugin is this about?**
MemberCount

**Describe the Bug**
When loading the plugin, it gives the following error:
TypeError: Cannot destructure property 'useStateFromStores' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/MemberCount.plugin.js:172:11)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:886:5)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:887:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by jonesy-b-dev** [comment]
i have still the same issue

**Comment by jonesy-b-dev** [comment]
``` js
TypeError: Cannot destructure property 'useStateFromStores' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/MemberCount.plugin.js:172:11)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:886:5)
    at eval (betterdiscord://plugins/MemberCount.plugin.js:887:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by TheEmbracedOne** [comment]
> ```js
> TypeError: Cannot destructure property 'useStateFromStores' of 'WebpackModules.getByProps(...)' as it is undefined.
>     at buildPlugin (betterdiscord://plugins/MemberCount.plugin.js:172:11)
>     at eval (betterdiscord://plugins/MemberCount.plugin.js:886:5)
>     at eval (betterdiscord://plugins/MemberCount.plugin.js:887:3)
>     at N.requireAddon (betterdiscord/renderer.js:5:28601)
>     at N.loadAddon (betterdiscord/renderer.js:5:6221)
>     at N.loadAddon (betterdiscord/renderer.js:5:26269)
>     at betterdiscord/renderer.js:5:4201
> ```

try reinstalling the plugin. The latest update fixed it for me.

**Comment by jonesy-b-dev** [comment]
Reinstalling did sadly not work for me. 
Just to be sure what version are you on?
I'm on `v2.2.20`

**Comment by Arashiryuu** [comment]
> Reinstalling did sadly not work for me. Just to be sure what version are you on? I'm on `v2.2.20`

Latest is `2.2.21` but the BetterDiscord website will probably be a while before someone gets around to reviewing the changes and updating their version.

You can get the current version from here by saving the [raw](https://raw.githubusercontent.com/Arashiryuu/crap/master/ToastIntegrated/MemberCount/MemberCount.plugin.js) via right click -> "Save as", or the `Ctrl`+`S` keybind

**Comment by jonesy-b-dev** [comment]
Yeap this version worked thanks a lot
