### ISSUE TITLE
[Bug] HideUtils Broken

### ISSUE THREAD

**Issue by jammerxd** [Arashiryuu/crap#231]
**Which plugin is this about?**
HideUtils

**Describe the Bug**
Fails to be compiled when launching BetterDiscord

**To Reproduce**
Download and install plugin
Close BetterDiscord
Relaunch BetterDiscord

**Expected Behavior**
Context menu for hiding servers, channels, and users appears

**Discord Version**
Stable

**Additional Context**
```
TypeError: Cannot destructure property 'ComponentDispatch' of 'WebpackModules.getByProps(...)' as it is undefined.
    at buildPlugin (betterdiscord://plugins/HideUtils.plugin.js:120:30)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1547:5)
    at eval (betterdiscord://plugins/HideUtils.plugin.js:1548:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by angsaysroar** [comment]
Does anyone know if this has been forked or should this be marked as officially abandoned?

**Comment by ColbyDash** [comment]
This should be marked as officially abandoned at this point as it seems to have been ongoing since 2022 going by [this issue thread.](https://github.com/Arashiryuu/crap/issues/195)
